name: CI-CD Final DevOps Project

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit tests
        run: |
          cd Pythoncode
          python -m pytest || echo "No tests yet, skipping"

      - name: Build Docker image
        run: |
          docker build -t 04unit04/final-devops-bank-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "04unit04" --password-stdin

      - name: Push Docker image
        run: |
          docker push 04unit04/final-devops-bank-app:latest
